import { Exercise } from '../types/domain.types';

export const STARTER_EXERCISES: Exercise[] = [
  // CHEST / PUSH
  {
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Lie flat on the bench with eyes under the barbell. Retract shoulder blades, grip slightly wider than shoulder-width, plant feet firmly. Unrack, lower under control to mid-chest, and press explosively back to lockout.',
    commonMistakes: [
      'Flaring elbows outward at 90 degrees to torso',
      'Bouncing the barbell off the sternum',
      'Lifting hips off the bench during leg drive',
    ],
    suitableAlternatives: ['ex-incline-db-press', 'ex-dips-chest', 'ex-pushups'],
    isCustom: false,
  },
  {
    id: 'ex-incline-db-press',
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'DUMBBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Set bench to a 30-to-45 degree incline. Hold dumbbells over upper chest with palms forward. Lower dumbbells steadily until thumbs align with upper chest, then press upward in a slight arc.',
    commonMistakes: [
      'Setting bench angle steeper than 45 degrees (shifts work to front deltoids)',
      'Over-arching lower back to flatten the angle',
      'Dropping dumbbells too deep causing excessive anterior shoulder strain',
    ],
    suitableAlternatives: ['ex-bench-press', 'ex-dips-chest', 'ex-pushups'],
    isCustom: false,
  },
  {
    id: 'ex-decline-bench-press',
    name: 'Decline Barbell Bench Press',
    slug: 'decline-barbell-bench-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Secure ankles under roller pads on decline bench. Lie back with shoulder blades pinned. Unrack bar, lower smoothly to lower chest crease, and press upward.',
    commonMistakes: [
      'Failing to lock feet securely into ankle pads',
      'Lowering the bar too high across the neck instead of lower chest',
    ],
    suitableAlternatives: ['ex-bench-press', 'ex-dips-chest'],
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-fly',
    name: 'Dumbbell Chest Fly',
    slug: 'dumbbell-chest-fly',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Lie on flat bench holding dumbbells with neutral palms. Keep a fixed slight bend in elbows. Open arms laterally in a wide arc until deep chest stretch, then squeeze pectorals to bring weights together.',
    commonMistakes: [
      'Excessive elbow bending turning the movement into a bench press',
      'Overstretching shoulder capsule below bench level',
    ],
    suitableAlternatives: ['ex-cable-crossover'],
    isCustom: false,
  },
  {
    id: 'ex-cable-crossover',
    name: 'Cable Crossover',
    slug: 'cable-crossover',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Set pulleys to shoulder or high height. Step forward into staggered stance with slight forward torso lean. Bring handles together in hugging motion, crossing hands slightly for maximal contraction.',
    commonMistakes: [
      'Using torso swing and body momentum to heave the cables',
      'Incomplete chest contraction across the midline',
    ],
    suitableAlternatives: ['ex-dumbbell-fly'],
    isCustom: false,
  },
  {
    id: 'ex-dips-chest',
    name: 'Chest Dips',
    slug: 'chest-dips',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'ADVANCED',
    instructions: 'Grip parallel dip bars. Lean torso forward approximately 30 degrees with elbows flared slightly outward. Descend until shoulders are level with elbows, then push through palms to return to top.',
    commonMistakes: [
      'Remaining fully upright (shifts emphasis entirely to triceps)',
      'Descending excessively deep into anterior shoulder impingement',
      'Shrugging shoulders into ears at top lockout',
    ],
    suitableAlternatives: ['ex-bench-press', 'ex-pushups', 'ex-incline-db-press'],
    isCustom: false,
  },
  {
    id: 'ex-pushups',
    name: 'Push-Up',
    slug: 'push-up',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Core', 'Front Delts'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'ACCESSORY',
    difficulty: 'BEGINNER',
    instructions: 'Assume strong high plank position with hands slightly outside shoulders. Brace abs and glutes. Lower chest to floor with elbows tracking back at 45 degrees, then drive floor away to full lockout.',
    commonMistakes: [
      'Sagging lower back and pelvis out of neutral alignment',
      'Flaring elbows out perpendicular to torso',
      'Half-reps without chest approaching floor',
    ],
    suitableAlternatives: ['ex-bench-press', 'ex-dips-chest'],
    isCustom: false,
  },

  // BACK / PULL
  {
    id: 'ex-barbell-deadlift',
    name: 'Conventional Barbell Deadlift',
    slug: 'conventional-barbell-deadlift',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Traps', 'Forearms'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Stand with feet hip-width, barbell over mid-foot. Hinge hips back, grip bar outside shins, pull chest tall to set lats and brace core. Push floor away through heels, locking hips and knees together.',
    commonMistakes: [
      'Rounding lumbar spine during the initial pull off the floor',
      'Bar drifting forward away from contact with shins and thighs',
      'Hyperextending spine backward at lockout instead of standing tall with glute squeeze',
    ],
    suitableAlternatives: ['ex-sumo-deadlift', 'ex-romanian-deadlift', 'ex-kb-swing'],
    isCustom: false,
  },
  {
    id: 'ex-sumo-deadlift',
    name: 'Sumo Deadlift',
    slug: 'sumo-deadlift',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Glutes', 'Adductors', 'Hamstrings', 'Traps'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Wide stance with feet turned outward toward plates. Grip bar inside knees with vertical shins. Keep chest upright, spread floor apart with feet, drive hips forward to lockout.',
    commonMistakes: [
      'Hips shooting up first before bar leaves floor',
      'Knees caving inward during off-the-floor phase',
    ],
    suitableAlternatives: ['ex-barbell-deadlift', 'ex-romanian-deadlift'],
    isCustom: false,
  },
  {
    id: 'ex-pullup',
    name: 'Pull-Up',
    slug: 'pull-up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back', 'Forearms'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Pronated (overhand) grip slightly wider than shoulders. Hang in full extension, depress scapulae, drive elbows down toward ribcage until chin clears above the bar. Lower under complete control.',
    commonMistakes: [
      'Excessive kipping and body swing',
      'Failing to reach full deadhang stretch at the bottom',
      'Reaching with neck rather than pulling chest toward bar',
    ],
    suitableAlternatives: ['ex-chinup', 'ex-lat-pulldown', 'ex-barbell-row'],
    isCustom: false,
  },
  {
    id: 'ex-chinup',
    name: 'Chin-Up',
    slug: 'chin-up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Forearms'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Supinated (underhand) grip shoulder-width apart. Hang in full stretch, pull chest toward bar with elbows tucked, emphasizing bicep and lat contraction at the apex.',
    commonMistakes: [
      'Cutting bottom range of motion short',
      'Excessive forward shoulder rolling at top contraction',
    ],
    suitableAlternatives: ['ex-pullup', 'ex-lat-pulldown', 'ex-seated-cable-row'],
    isCustom: false,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Bent-Over Row',
    slug: 'barbell-bent-over-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Rear Delts', 'Spinal Erectors'],
    equipment: 'BARBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Hinge hips back to approximately 45 degrees with flat spine and braced core. Grip barbell shoulder-width, pull bar toward lower ribcage/navel by driving elbows back, squeeze scapulae together.',
    commonMistakes: [
      'Using torso jerking and hip momentum to bounce weight upward',
      'Rounding lumbar spine under heavy load',
      'Pulling too high to collarbone rather than lower abdomen',
    ],
    suitableAlternatives: ['ex-tbar-row', 'ex-seated-cable-row', 'ex-db-single-arm-row'],
    isCustom: false,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'CABLE',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'BEGINNER',
    instructions: 'Secure thighs firmly under pads. Grip wide bar outside shoulders. Lean back roughly 10 degrees, retract scapulae, drive elbows straight down until bar reaches upper chest. Return under control.',
    commonMistakes: [
      'Leaning back 45+ degrees turning the exercise into a horizontal row',
      'Pulling the bar behind the neck (stresses cervical spine and rotator cuff)',
      'Using forearm grip rather than driving through the elbows',
    ],
    suitableAlternatives: ['ex-pullup', 'ex-chinup', 'ex-seated-cable-row'],
    isCustom: false,
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Rear Delts'],
    equipment: 'CABLE',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'BEGINNER',
    instructions: 'Sit with feet braced, knees slightly bent, chest tall. Grip handle, pull into lower abdomen while driving elbows backward and pinching shoulder blades. Extend arms smoothly without rounding lower back.',
    commonMistakes: [
      'Excessive backward and forward torso rocking',
      'Shrugging shoulders into ears at contraction point',
    ],
    suitableAlternatives: ['ex-barbell-row', 'ex-tbar-row', 'ex-db-single-arm-row'],
    isCustom: false,
  },
  {
    id: 'ex-db-single-arm-row',
    name: 'Single-Arm Dumbbell Row',
    slug: 'single-arm-dumbbell-row',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Rhomboids', 'Rear Delts'],
    equipment: 'DUMBBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'BEGINNER',
    instructions: 'Place one knee and hand on flat bench for torso support. Hold dumbbell with free hand hanging straight down. Pull dumbbell in an arc toward hip crease, squeezing lat at peak.',
    commonMistakes: [
      'Rotating torso excessively to heave dumbbell upward',
      'Pulling directly up to chest rather than sweeping back to hip',
    ],
    suitableAlternatives: ['ex-seated-cable-row', 'ex-barbell-row', 'ex-tbar-row'],
    isCustom: false,
  },
  {
    id: 'ex-tbar-row',
    name: 'T-Bar Row',
    slug: 't-bar-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Traps', 'Biceps'],
    equipment: 'BARBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Straddle T-bar machine or landmine barbell. Hinge at hips with flat back. Grip handles and pull upward to lower chest, driving shoulder blades together.',
    commonMistakes: [
      'Rounding lumbar spine at the bottom hinge',
      'Standing too upright and cutting horizontal pull angle',
    ],
    suitableAlternatives: ['ex-barbell-row', 'ex-seated-cable-row'],
    isCustom: false,
  },

  // LEGS / SQUAT / HINGE
  {
    id: 'ex-barbell-back-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core', 'Calves'],
    equipment: 'BARBELL',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Rest barbell across upper traps or rear delts. Step back, feet shoulder-width, toes slightly out. Inhale and brace 360 degrees. Descend hips back and down until hip crease drops below kneecaps. Drive forcefully out of the hole through mid-foot.',
    commonMistakes: [
      'Knees collapsing inward (valgus collapse) out of the hole',
      'Heels lifting off floor shifting load excessively to knees',
      'Rounding lumbar spine (butt wink) at maximum depth',
    ],
    suitableAlternatives: ['ex-barbell-front-squat', 'ex-leg-press', 'ex-bulgarian-split-squat'],
    isCustom: false,
  },
  {
    id: 'ex-barbell-front-squat',
    name: 'Barbell Front Squat',
    slug: 'barbell-front-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Core', 'Upper Back'],
    equipment: 'BARBELL',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Rest barbell across anterior deltoids in clean grip or cross-arm rack with high elbows. Squat down with upright torso to full depth, then drive upward keeping elbows elevated.',
    commonMistakes: [
      'Dropping elbows forward causing the bar to slip off shoulders',
      'Collapsing chest inward instead of maintaining thoracic extension',
    ],
    suitableAlternatives: ['ex-barbell-back-squat', 'ex-leg-press', 'ex-bulgarian-split-squat'],
    isCustom: false,
  },
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    slug: 'romanian-deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Lower Back', 'Core'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Stand tall with slight soft bend in knees. Hinge hips backward as barbell skims down along thighs and shins. Stop once hamstrings are fully stretched and hips stop traveling back. Squeeze glutes and drive hips forward to return.',
    commonMistakes: [
      'Squatting with deep knee bend instead of hinging hips back',
      'Letting the barbell drift forward away from legs',
      'Rounding back to reach floor rather than stopping at hamstring stretch',
    ],
    suitableAlternatives: ['ex-barbell-deadlift', 'ex-lying-leg-curl', 'ex-kb-swing'],
    isCustom: false,
  },
  {
    id: 'ex-leg-press',
    name: '45° Leg Press',
    slug: '45-leg-press',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'MACHINE',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'BEGINNER',
    instructions: 'Sit in sled with back and head flat against pads. Position feet shoulder-width on platform. Disengage safety catches, lower platform until knees are at 90 degrees without lower back peeling off pad, press back up without hyper-locking knees.',
    commonMistakes: [
      'Placing feet too low on platform causing excessive patellar shearing',
      'Hyperextending knees aggressively at lockout',
      'Descending so deep that lower back and pelvis peel off the seat pad',
    ],
    suitableAlternatives: ['ex-barbell-back-squat', 'ex-leg-extension', 'ex-bulgarian-split-squat'],
    isCustom: false,
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    slug: 'bulgarian-split-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Adductors', 'Calves'],
    equipment: 'DUMBBELL',
    movementPattern: 'LUNGE',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Elevate rear foot on bench behind you. Hold dumbbells at sides. Lower rear knee toward floor until front thigh is parallel to floor. Drive through front heel to return to top.',
    commonMistakes: [
      'Stance distance too short or too long causing balance instability',
      'Front knee caving inward during descent',
      'Leaning torso excessively backward compressing lumbar spine',
    ],
    suitableAlternatives: ['ex-barbell-back-squat', 'ex-leg-press'],
    isCustom: false,
  },
  {
    id: 'ex-hip-thrust',
    name: 'Barbell Hip Thrust',
    slug: 'barbell-hip-thrust',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings', 'Core'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Sit on floor with upper back against bench and padded barbell over hips. Bend knees at 90 degrees at top. Drive hips upward until thighs and torso form horizontal bridge, hold peak contraction for 1 second.',
    commonMistakes: [
      'Hyperextending lumbar spine at top instead of posterior pelvic tilt',
      'Failing to reach full horizontal hip extension',
      'Looking up at ceiling instead of maintaining chin tucked forward',
    ],
    suitableAlternatives: ['ex-romanian-deadlift', 'ex-barbell-deadlift'],
    isCustom: false,
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension',
    slug: 'leg-extension',
    primaryMuscle: 'Quads',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Sit with back flat against backrest and pad resting across lower shins. Extend knees smoothly until legs are straight, pause to peak quadriceps contraction, lower slowly.',
    commonMistakes: [
      'Kicking weight up with jerky, explosive momentum',
      'Misaligning machine pivot point with the natural knee axis',
    ],
    suitableAlternatives: ['ex-leg-press', 'ex-bulgarian-split-squat'],
    isCustom: false,
  },
  {
    id: 'ex-lying-leg-curl',
    name: 'Lying Leg Curl',
    slug: 'lying-leg-curl',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Lie face down with roller pad positioned just below calf muscles. Grasp handles, curl pad toward glutes while keeping pelvis pressed flat into bench. Lower slowly under full control.',
    commonMistakes: [
      'Allowing hips to rise up off the bench during contraction',
      'Excessive lower back hyperextension during effort',
    ],
    suitableAlternatives: ['ex-romanian-deadlift'],
    isCustom: false,
  },
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    slug: 'standing-calf-raise',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Place balls of feet on block edge, shoulders under padded levers. Lower heels into deep stretch, pause 1 second, drive up onto big toes to maximum contraction, hold 1 second.',
    commonMistakes: [
      'Bouncing rapidly using Achilles tendon recoil without pausing',
      'Incomplete range of motion at bottom stretch',
    ],
    suitableAlternatives: [],
    isCustom: false,
  },

  // SHOULDERS / DELTOIDS
  {
    id: 'ex-overhead-press',
    name: 'Overhead Press (OHP)',
    slug: 'overhead-press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Core'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    difficulty: 'ADVANCED',
    instructions: 'Stand tall with feet shoulder-width. Hold barbell on front delts, grip just outside shoulders. Squeeze glutes and brace core. Press bar vertically overhead, moving head back then forward once bar clears forehead to lock out overhead.',
    commonMistakes: [
      'Excessive backward spinal arching turning lift into an incline press',
      'Pressing bar in looping arc around face instead of clearing chin',
      'Flaring elbows outward excessively during press phase',
    ],
    suitableAlternatives: ['ex-dumbbell-shoulder-press'],
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    slug: 'seated-dumbbell-shoulder-press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest'],
    equipment: 'DUMBBELL',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Sit on upright bench with dumbbells at shoulder height, elbows angled 30 degrees forward in scapular plane. Press overhead in smooth arc until arms are extended, lower slowly.',
    commonMistakes: [
      'Pressing with elbows flared completely flat against the frontal plane',
      'Over-arching lumbar spine off the backrest',
    ],
    suitableAlternatives: ['ex-overhead-press'],
    isCustom: false,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: ['Traps'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Stand tall holding dumbbells at sides with slight forward lean. Lead with elbows in scapular plane, raise arms out until parallel to floor, pour slightly as if pouring water, and lower slowly.',
    commonMistakes: [
      'Swinging hips and shrugging upper traps to heave heavy dumbbells',
      'Raising wrists higher than elbows causing shoulder internal impingement',
    ],
    suitableAlternatives: ['ex-cable-lateral-raise'],
    isCustom: false,
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    slug: 'cable-lateral-raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: ['Traps'],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Set low pulley with single handle. Stand sideways, reach across body to grip handle. Raise arm outward in scapular plane for constant tension on lateral head of deltoid.',
    commonMistakes: [
      'Leading with hands rather than elbows',
      'Using torso momentum to initiate cable movement',
    ],
    suitableAlternatives: ['ex-lateral-raise'],
    isCustom: false,
  },
  {
    id: 'ex-face-pull',
    name: 'Cable Face Pull',
    slug: 'cable-face-pull',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Rotator Cuff', 'Upper Back', 'Rhomboids'],
    equipment: 'CABLE',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'ACCESSORY',
    difficulty: 'BEGINNER',
    instructions: 'Attach rope to high pulley. Grip rope with thumbs pointing toward back. Step back, pull center of rope toward bridge of nose while externally rotating shoulders so knuckles face backward.',
    commonMistakes: [
      'Using excessive weight and leaning backward to counterbalance',
      'Failing to externally rotate at finish (thumbs must point backward)',
    ],
    suitableAlternatives: ['ex-reverse-pec-deck'],
    isCustom: false,
  },
  {
    id: 'ex-reverse-pec-deck',
    name: 'Reverse Pec Deck Fly',
    slug: 'reverse-pec-deck-fly',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Rhomboids', 'Traps'],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Sit facing machine with chest firmly against pad. Adjust handles to shoulder height. Grasp neutral handles, sweep arms backward in horizontal plane, squeezing rear deltoids at peak.',
    commonMistakes: [
      'Shrugging traps and turning exercise into upper trap shrug',
      'Bending elbows excessively during contraction',
    ],
    suitableAlternatives: ['ex-face-pull'],
    isCustom: false,
  },

  // ARMS (BICEPS & TRICEPS)
  {
    id: 'ex-barbell-bicep-curl',
    name: 'Barbell Bicep Curl',
    slug: 'barbell-bicep-curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Brachialis', 'Forearms'],
    equipment: 'BARBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Stand tall with supinated shoulder-width grip on straight or EZ bar. Pin elbows to sides, curl barbell upward toward shoulders, squeeze biceps at top, lower slowly over 2-3 seconds.',
    commonMistakes: [
      'Swinging hips and throwing elbows forward to complete reps',
      'Dropping bar quickly without resisting eccentric descent',
    ],
    suitableAlternatives: ['ex-incline-db-curl', 'ex-dumbbell-hammer-curl'],
    isCustom: false,
  },
  {
    id: 'ex-incline-db-curl',
    name: 'Incline Dumbbell Curl',
    slug: 'incline-dumbbell-curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Brachialis', 'Forearms'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'INTERMEDIATE',
    instructions: 'Set bench to 45-60 degree incline. Lie back with arms hanging straight down for deep stretch on bicep long head. Curl dumbbells upward while supinating wrists, squeeze at top, descend under control.',
    commonMistakes: [
      'Lifting shoulders and head off bench',
      'Setting bench angle too flat causing anterior shoulder capsule strain',
    ],
    suitableAlternatives: ['ex-barbell-bicep-curl', 'ex-dumbbell-hammer-curl'],
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    slug: 'dumbbell-hammer-curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Brachialis', 'Forearms'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Stand tall holding dumbbells with neutral palms facing each other. Keep elbows tucked, curl dumbbells toward shoulders, squeeze brachialis at top, lower steadily.',
    commonMistakes: [
      'Using torso swinging to curl weights',
      'Pronating wrists during curl motion',
    ],
    suitableAlternatives: ['ex-barbell-bicep-curl', 'ex-incline-db-curl'],
    isCustom: false,
  },
  {
    id: 'ex-barbell-skull-crusher',
    name: 'Barbell Skull Crusher',
    slug: 'barbell-skull-crusher',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'BARBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'INTERMEDIATE',
    instructions: 'Lie flat on bench holding EZ bar with narrow overhand grip over chest. Angle upper arms slightly back toward head. Bend elbows to lower bar toward forehead or crown of head, extend elbows back to lockout.',
    commonMistakes: [
      'Flaring elbows outward to the sides',
      'Letting upper arms drift forward and backward instead of remaining stationary',
    ],
    suitableAlternatives: ['ex-triceps-cable-rope-pushdown', 'ex-overhead-cable-triceps-extension'],
    isCustom: false,
  },
  {
    id: 'ex-triceps-cable-rope-pushdown',
    name: 'Triceps Cable Rope Pushdown',
    slug: 'triceps-cable-rope-pushdown',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Attach rope to high pulley. Stand with elbows pinned to sides. Push rope down toward hips, spreading rope ends apart at the bottom to maximize lateral and medial head triceps contraction.',
    commonMistakes: [
      'Allowing elbows to flare or drift forward during repetition',
      'Leaning body excessively over the rope',
    ],
    suitableAlternatives: ['ex-barbell-skull-crusher', 'ex-overhead-cable-triceps-extension'],
    isCustom: false,
  },
  {
    id: 'ex-overhead-cable-triceps-extension',
    name: 'Overhead Cable Triceps Extension',
    slug: 'overhead-cable-triceps-extension',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'INTERMEDIATE',
    instructions: 'Attach rope to medium or high pulley. Turn away from stack in forward lunge stance. Hold rope behind head with elbows bent, extend arms forward overhead for complete stretch and peak triceps long head contraction.',
    commonMistakes: [
      'Arching lower back excessively against the cable pull',
      'Flaring elbows wide out of alignment',
    ],
    suitableAlternatives: ['ex-triceps-cable-rope-pushdown', 'ex-barbell-skull-crusher'],
    isCustom: false,
  },

  // CORE
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Forearms'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'ISOLATION',
    tier: 'ACCESSORY',
    difficulty: 'ADVANCED',
    instructions: 'Hang from pull-up bar with overhand grip. Engage core to prevent swing. Raise straight legs until toes reach bar level by actively curling pelvis toward chest. Lower slowly without swinging.',
    commonMistakes: [
      'Swinging body with pendulum momentum',
      'Only flexing hips without posterior pelvic curling of the abs',
    ],
    suitableAlternatives: ['ex-cable-kneeling-crunch', 'ex-ab-wheel-rollout'],
    isCustom: false,
  },
  {
    id: 'ex-cable-kneeling-crunch',
    name: 'Cable Kneeling Crunch',
    slug: 'cable-kneeling-crunch',
    primaryMuscle: 'Core',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    difficulty: 'BEGINNER',
    instructions: 'Kneel in front of high cable with rope held beside ears. Fix hips in place. Contract abdominal wall to curl torso downward, bringing elbows toward knees. Slowly return to start.',
    commonMistakes: [
      'Sitting hips back onto heels instead of flexing the spine',
      'Pulling rope with arms instead of crunching with core',
    ],
    suitableAlternatives: ['ex-hanging-leg-raise', 'ex-ab-wheel-rollout'],
    isCustom: false,
  },
  {
    id: 'ex-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    slug: 'ab-wheel-rollout',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Lats', 'Shoulders'],
    equipment: 'OTHER',
    movementPattern: 'ISOLATION',
    tier: 'ACCESSORY',
    difficulty: 'ADVANCED',
    instructions: 'Kneel with ab wheel directly under shoulders. Brace abs with slight posterior pelvic tilt. Roll wheel forward smoothly as far as you can maintain a flat back, pull back using core contraction.',
    commonMistakes: [
      'Allowing lower back to hyperextend into lumbar pain',
      'Bending hips back first rather than initiating pull with the core',
    ],
    suitableAlternatives: ['ex-hanging-leg-raise', 'ex-cable-kneeling-crunch'],
    isCustom: false,
  },

  // CARDIO & POWER
  {
    id: 'ex-running',
    name: 'Running',
    slug: 'running',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Calves', 'Cardio'],
    equipment: 'OTHER',
    movementPattern: 'CARDIO',
    tier: 'ACCESSORY',
    difficulty: 'BEGINNER',
    instructions: 'Maintain steady cadenced stride, upright spine, forward gaze, and rhythmic aerobic breathing.',
    commonMistakes: [
      'Overstriding with harsh heel impact',
      'Slouching posture reducing diaphragmatic expansion',
    ],
    suitableAlternatives: ['ex-cycling', 'ex-rowing'],
    isCustom: false,
  },
  {
    id: 'ex-cycling',
    name: 'Cycling',
    slug: 'cycling',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Hamstrings', 'Cardio'],
    equipment: 'MACHINE',
    movementPattern: 'CARDIO',
    tier: 'ACCESSORY',
    difficulty: 'BEGINNER',
    instructions: 'Adjust saddle to hip height with slight knee bend at bottom pedal stroke. Maintain consistent RPM cadence and targeted power output.',
    commonMistakes: [
      'Saddle height too low placing excessive shear force on patella',
      'Rocking hips violently from side to side',
    ],
    suitableAlternatives: ['ex-running', 'ex-rowing'],
    isCustom: false,
  },
  {
    id: 'ex-rowing',
    name: 'Rowing Machine',
    slug: 'rowing-machine',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Legs', 'Cardio', 'Lats'],
    equipment: 'MACHINE',
    movementPattern: 'CARDIO',
    tier: 'ACCESSORY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Drive first with legs, swing hips open once knees pass, pull handle to lower ribs. Reverse sequence smoothly: arms, hips, then knees bend.',
    commonMistakes: [
      'Pulling with arms before leg drive is complete',
      'Rounding back at the catch position',
    ],
    suitableAlternatives: ['ex-running', 'ex-cycling'],
    isCustom: false,
  },
  {
    id: 'ex-kb-swing',
    name: 'Kettlebell Swing',
    slug: 'kettlebell-swing',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Core', 'Traps', 'Forearms'],
    equipment: 'KETTLEBELL',
    movementPattern: 'HINGE',
    tier: 'ACCESSORY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Hinge back deeply with bell between knees and shins nearly vertical. Snap hips forward explosively, projecting bell to chest height through glute force.',
    commonMistakes: [
      'Squatting the kettlebell instead of hinging hips back',
      'Raising bell with shoulders and arms instead of hip snap',
    ],
    suitableAlternatives: ['ex-romanian-deadlift', 'ex-barbell-deadlift'],
    isCustom: false,
  },
  {
    id: 'ex-box-jump',
    name: 'Box Jump',
    slug: 'box-jump',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Calves', 'Glutes', 'Hamstrings'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'SQUAT',
    tier: 'ACCESSORY',
    difficulty: 'INTERMEDIATE',
    instructions: 'Stand facing sturdy box. Drop into athletic quarter-squat, explode upward swinging arms, land softly on box in balanced quarter-squat.',
    commonMistakes: [
      'Landing stiff-legged with harsh joint impact',
      'Choosing too tall a box leading to severe hip flexion crashes',
    ],
    suitableAlternatives: ['ex-barbell-back-squat'],
    isCustom: false,
  },
];

export function inferProgressionType(ex: Pick<Exercise, 'equipment' | 'tier' | 'movementPattern'>) {
  if (ex.movementPattern === 'CARDIO') {
    return {
      progressionType: 'CARDIO' as const,
      supports1Rm: false,
      supportsRelativeStrength: false,
      isBodyweight: false,
    };
  }
  if (ex.movementPattern === 'ATHLETIC' || ex.equipment === 'KETTLEBELL') {
    return {
      progressionType: 'ATHLETIC' as const,
      supports1Rm: false,
      supportsRelativeStrength: false,
      isBodyweight: false,
    };
  }
  if (ex.equipment === 'BODYWEIGHT') {
    return {
      progressionType: 'BODYWEIGHT' as const,
      supports1Rm: false,
      supportsRelativeStrength: false,
      isBodyweight: true,
    };
  }
  if (ex.equipment === 'MACHINE') {
    return {
      progressionType: 'MACHINE' as const,
      supports1Rm: false,
      supportsRelativeStrength: false,
      isBodyweight: false,
    };
  }
  if (ex.tier === 'ISOLATION' || ex.movementPattern === 'ISOLATION') {
    return {
      progressionType: 'ISOLATION' as const,
      supports1Rm: false,
      supportsRelativeStrength: false,
      isBodyweight: false,
    };
  }
  if (ex.equipment === 'BARBELL') {
    return {
      progressionType: 'BARBELL_COMPOUND' as const,
      supports1Rm: true,
      supportsRelativeStrength: true,
      isBodyweight: false,
    };
  }
  if (ex.equipment === 'DUMBBELL') {
    return {
      progressionType: 'DUMBBELL_COMPOUND' as const,
      supports1Rm: true,
      supportsRelativeStrength: false,
      isBodyweight: false,
    };
  }
  return {
    progressionType: 'ISOLATION' as const,
    supports1Rm: false,
    supportsRelativeStrength: false,
    isBodyweight: false,
  };
}

// Ensure all starter exercises are enriched
for (const ex of STARTER_EXERCISES) {
  const inferred = inferProgressionType(ex);
  ex.progressionType = ex.progressionType || inferred.progressionType;
  ex.supports1Rm = ex.supports1Rm !== undefined ? ex.supports1Rm : inferred.supports1Rm;
  ex.supportsRelativeStrength = ex.supportsRelativeStrength !== undefined ? ex.supportsRelativeStrength : inferred.supportsRelativeStrength;
  ex.isBodyweight = ex.isBodyweight !== undefined ? ex.isBodyweight : inferred.isBodyweight;
  ex.difficulty = ex.difficulty || 'INTERMEDIATE';
  ex.commonMistakes = ex.commonMistakes || [];
  ex.suitableAlternatives = ex.suitableAlternatives || [];
}
