import { Exercise } from '../types/domain.types';

export const STARTER_EXERCISES: Exercise[] = [
  // CHEST / PUSH
  {
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    slug: 'barbell-bench-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Lie on the bench with eyes under the bar. Grip the bar slightly wider than shoulder-width. Lower bar to mid-chest, drive up explosively.',
    isCustom: false,
  },
  {
    id: 'ex-incline-db-press',
    name: 'Incline Dumbbell Press',
    slug: 'incline-dumbbell-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipment: 'DUMBBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Set bench to 30 degrees. Press dumbbells upward over chest, squeeze clavicular pectorals at the peak.',
    isCustom: false,
  },
  {
    id: 'ex-decline-bench-press',
    name: 'Decline Barbell Bench Press',
    slug: 'decline-barbell-bench-press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Secure feet at the top of the decline bench. Lower the barbell to the lower chest, press upward.',
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-fly',
    name: 'Dumbbell Chest Fly',
    slug: 'dumbbell-chest-fly',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Lie on flat bench with slight elbow bend. Open arms wide to feel chest stretch, bring dumbbells together in hugging arc.',
    isCustom: false,
  },
  {
    id: 'ex-cable-crossover',
    name: 'Cable Crossover',
    slug: 'cable-crossover',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Set high pulleys. Step forward in staggered stance, pull handles down and together across midline.',
    isCustom: false,
  },
  {
    id: 'ex-dips-chest',
    name: 'Chest Dips',
    slug: 'chest-dips',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Grip parallel bars, lean torso forward 30 degrees, lower body until shoulders are below elbows, press back up.',
    isCustom: false,
  },
  {
    id: 'ex-pushups',
    name: 'Push-Up',
    slug: 'push-up',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Core'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PUSH_HORIZONTAL',
    tier: 'ACCESSORY',
    instructions: 'Plank posture, hands shoulder-width. Lower chest to floor with elbows at 45 degrees, press to lockout.',
    isCustom: false,
  },

  // BACK / PULL
  {
    id: 'ex-barbell-deadlift',
    name: 'Conventional Barbell Deadlift',
    slug: 'conventional-barbell-deadlift',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Traps', 'Forearms'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Stand mid-foot under bar. Hinge hips back, grip bar outside shins, brace core, push floor away to full hip extension.',
    isCustom: false,
  },
  {
    id: 'ex-sumo-deadlift',
    name: 'Sumo Deadlift',
    slug: 'sumo-deadlift',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Glutes', 'Adductors', 'Hamstrings', 'Traps'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Wide stance with toes flared. Grip bar inside knees. Drive knees out, push floor away with upright torso.',
    isCustom: false,
  },
  {
    id: 'ex-pullup',
    name: 'Pull-Up',
    slug: 'pull-up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Overhand grip slightly wider than shoulders. Depress scaps, drive elbows down to ribs until chin clears bar.',
    isCustom: false,
  },
  {
    id: 'ex-chinup',
    name: 'Chin-Up',
    slug: 'chin-up',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Forearms'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Supinated grip shoulder-width. Pull chest toward bar, emphasizing bicep and lower lat contraction.',
    isCustom: false,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Bent-Over Row',
    slug: 'barbell-bent-over-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps', 'Rear Delts', 'Spinal Erectors'],
    equipment: 'BARBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Hinge at hips to 45 degrees with flat spine. Pull barbell towards lower abdomen, pinching shoulder blades.',
    isCustom: false,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    slug: 'lat-pulldown',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Upper Back'],
    equipment: 'CABLE',
    movementPattern: 'PULL_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Sit securely under thigh pads. Pull wide bar downward to upper chest while leaning back slightly.',
    isCustom: false,
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    slug: 'seated-cable-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Biceps'],
    equipment: 'CABLE',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Sit with feet braced, pull V-bar or neutral attachment into stomach, squeezing mid-back.',
    isCustom: false,
  },
  {
    id: 'ex-db-single-arm-row',
    name: 'Single-Arm Dumbbell Row',
    slug: 'single-arm-dumbbell-row',
    primaryMuscle: 'Lats',
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    equipment: 'DUMBBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'One hand and knee on bench. Row dumbbell towards hip crease with elbow tucked.',
    isCustom: false,
  },
  {
    id: 'ex-tbar-row',
    name: 'T-Bar Row',
    slug: 't-bar-row',
    primaryMuscle: 'Upper Back',
    secondaryMuscles: ['Lats', 'Traps'],
    equipment: 'BARBELL',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Straddle landmine or T-bar machine. Pull handles to chest while maintaining neutral spine.',
    isCustom: false,
  },

  // LEGS / SQUAT / HINGE
  {
    id: 'ex-barbell-back-squat',
    name: 'Barbell Back Squat',
    slug: 'barbell-back-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipment: 'BARBELL',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Bar resting on upper traps or rear delts. Squat down hips below knees while keeping chest tall, drive up through mid-foot.',
    isCustom: false,
  },
  {
    id: 'ex-barbell-front-squat',
    name: 'Barbell Front Squat',
    slug: 'barbell-front-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Core', 'Upper Back'],
    equipment: 'BARBELL',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Bar resting across anterior deltoids with elbows high. Descend with vertical torso, drive up aggressively.',
    isCustom: false,
  },
  {
    id: 'ex-romanian-deadlift',
    name: 'Romanian Deadlift (RDL)',
    slug: 'romanian-deadlift',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Glutes', 'Lower Back'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Slight knee bend. Push hips back as barbell skims down shins, feeling deep hamstring stretch, thrust hips forward to finish.',
    isCustom: false,
  },
  {
    id: 'ex-leg-press',
    name: '45° Leg Press',
    slug: '45-leg-press',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Hamstrings'],
    equipment: 'MACHINE',
    movementPattern: 'SQUAT',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Feet shoulder-width on sled. Lower platform until knees reach 90 degrees, press without locking knees out.',
    isCustom: false,
  },
  {
    id: 'ex-bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    slug: 'bulgarian-split-squat',
    primaryMuscle: 'Quads',
    secondaryMuscles: ['Glutes', 'Adductors'],
    equipment: 'DUMBBELL',
    movementPattern: 'LUNGE',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Rear foot elevated on bench. Lower front hip until knee is nearly touching floor, drive through front heel.',
    isCustom: false,
  },
  {
    id: 'ex-hip-thrust',
    name: 'Barbell Hip Thrust',
    slug: 'barbell-hip-thrust',
    primaryMuscle: 'Glutes',
    secondaryMuscles: ['Hamstrings'],
    equipment: 'BARBELL',
    movementPattern: 'HINGE',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Upper back against bench, barbell padded across hips. Drive hips to full horizontal lockout, squeeze glutes.',
    isCustom: false,
  },
  {
    id: 'ex-leg-extension',
    name: 'Leg Extension',
    slug: 'leg-extension',
    primaryMuscle: 'Quads',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Pad across lower shins. Extend knees to full contraction, pause briefly, lower under control.',
    isCustom: false,
  },
  {
    id: 'ex-lying-leg-curl',
    name: 'Lying Leg Curl',
    slug: 'lying-leg-curl',
    primaryMuscle: 'Hamstrings',
    secondaryMuscles: ['Calves'],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Lie prone, pad above heels. Curl weight towards glutes without lifting hips off pad.',
    isCustom: false,
  },
  {
    id: 'ex-standing-calf-raise',
    name: 'Standing Calf Raise',
    slug: 'standing-calf-raise',
    primaryMuscle: 'Calves',
    secondaryMuscles: [],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Balls of feet on edge of block. Deep calf stretch at bottom, push through big toes to peak plantarflexion.',
    isCustom: false,
  },

  // SHOULDERS / DELTOIDS
  {
    id: 'ex-overhead-press',
    name: 'Overhead Press (OHP)',
    slug: 'overhead-press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Core'],
    equipment: 'BARBELL',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_PRIMARY',
    instructions: 'Stand tall with glutes and abs tight. Press bar overhead in straight path, pushing head forward at lockout.',
    isCustom: false,
  },
  {
    id: 'ex-dumbbell-shoulder-press',
    name: 'Seated Dumbbell Shoulder Press',
    slug: 'seated-dumbbell-shoulder-press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps'],
    equipment: 'DUMBBELL',
    movementPattern: 'PUSH_VERTICAL',
    tier: 'COMPOUND_SECONDARY',
    instructions: 'Sit on upright bench. Press dumbbells overhead until arms are extended, lower slowly to ear level.',
    isCustom: false,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    slug: 'dumbbell-lateral-raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: ['Traps'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Lead with elbows slightly forward in scapular plane. Raise weights to shoulder height, control descent.',
    isCustom: false,
  },
  {
    id: 'ex-cable-lateral-raise',
    name: 'Cable Lateral Raise',
    slug: 'cable-lateral-raise',
    primaryMuscle: 'Side Delts',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Low pulley, handle behind back or across body. Raise arm outward for constant tension on lateral deltoid.',
    isCustom: false,
  },
  {
    id: 'ex-face-pull',
    name: 'Cable Face Pull',
    slug: 'cable-face-pull',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Rotator Cuff', 'Upper Back'],
    equipment: 'CABLE',
    movementPattern: 'PULL_HORIZONTAL',
    tier: 'ACCESSORY',
    instructions: 'Rope attachment at eye level. Pull rope to bridge of nose while externally rotating shoulders.',
    isCustom: false,
  },
  {
    id: 'ex-reverse-pec-deck',
    name: 'Reverse Pec Deck Fly',
    slug: 'reverse-pec-deck-fly',
    primaryMuscle: 'Rear Delts',
    secondaryMuscles: ['Rhomboids'],
    equipment: 'MACHINE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Chest against pad. Drive handles backward in horizontal plane, squeezing posterior deltoids.',
    isCustom: false,
  },

  // ARMS / BICEPS & TRICEPS
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Bicep Curl',
    slug: 'barbell-bicep-curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipment: 'BARBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Stand tall with supinated grip shoulder-width. Curl bar upward keeping elbows pinned to ribs.',
    isCustom: false,
  },
  {
    id: 'ex-incline-db-curl',
    name: 'Incline Dumbbell Curl',
    slug: 'incline-dumbbell-curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: [],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Sit on 45° incline bench. Let arms hang behind torso for deep long-head bicep stretch, curl upward.',
    isCustom: false,
  },
  {
    id: 'ex-hammer-curl',
    name: 'Dumbbell Hammer Curl',
    slug: 'dumbbell-hammer-curl',
    primaryMuscle: 'Brachialis',
    secondaryMuscles: ['Biceps', 'Forearms'],
    equipment: 'DUMBBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Neutral grip (palms facing each other). Curl dumbbells upward to target forearm and brachialis thickness.',
    isCustom: false,
  },
  {
    id: 'ex-skull-crusher',
    name: 'Barbell Skull Crusher (Lying Triceps Extension)',
    slug: 'barbell-skull-crusher',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'BARBELL',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Lie on flat bench, lower EZ-bar toward forehead or slightly behind head, extend elbows to lockout.',
    isCustom: false,
  },
  {
    id: 'ex-tricep-rope-pushdown',
    name: 'Triceps Cable Rope Pushdown',
    slug: 'triceps-cable-rope-pushdown',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'High pulley with rope. Push down, spreading rope ends at the bottom for peak lateral tricep squeeze.',
    isCustom: false,
  },
  {
    id: 'ex-overhead-cable-extension',
    name: 'Overhead Cable Triceps Extension',
    slug: 'overhead-cable-triceps-extension',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Facing away from high pulley. Extend elbows forward and overhead, putting long head on full stretch.',
    isCustom: false,
  },

  // CORE / ABDOMINALS
  {
    id: 'ex-hanging-leg-raise',
    name: 'Hanging Leg Raise',
    slug: 'hanging-leg-raise',
    primaryMuscle: 'Abs',
    secondaryMuscles: ['Hip Flexors', 'Grip'],
    equipment: 'BODYWEIGHT',
    movementPattern: 'ISOLATION',
    tier: 'ACCESSORY',
    instructions: 'Hang from bar with active shoulders. Raise toes to bar or parallel without swinging torso.',
    isCustom: false,
  },
  {
    id: 'ex-cable-crunch',
    name: 'Cable Kneeling Crunch',
    slug: 'cable-kneeling-crunch',
    primaryMuscle: 'Abs',
    secondaryMuscles: [],
    equipment: 'CABLE',
    movementPattern: 'ISOLATION',
    tier: 'ISOLATION',
    instructions: 'Kneel holding rope beside ears. Curl ribcage toward pelvis, flexing rectus abdominis.',
    isCustom: false,
  },
  {
    id: 'ex-ab-wheel-rollout',
    name: 'Ab Wheel Rollout',
    slug: 'ab-wheel-rollout',
    primaryMuscle: 'Abs',
    secondaryMuscles: ['Lats', 'Shoulders'],
    equipment: 'OTHER',
    movementPattern: 'ISOLATION',
    tier: 'ACCESSORY',
    instructions: 'Kneel with wheel in hands. Roll forward keeping hollow body posterior pelvic tilt, pull back with core.',
    isCustom: false,
  },
];
