import { ExerciseMilestone } from '../types/domain.types';

export const DEFAULT_EXERCISE_MILESTONES: ExerciseMilestone[] = [
  // SQUAT (ex-barbell-back-squat)
  {
    id: 'ms-squat-40',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 40,
    rewardXp: 100,
    title: 'Squat 40kg',
    description: 'Achieve a 40 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-50',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 50,
    rewardXp: 150,
    title: 'Squat 50kg',
    description: 'Achieve a 50 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-60',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 60,
    rewardXp: 200,
    title: 'Squat 60kg',
    description: 'Achieve a 60 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-70',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 70,
    rewardXp: 250,
    title: 'Squat 70kg',
    description: 'Achieve a 70 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-80',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 80,
    rewardXp: 300,
    title: 'Squat 80kg',
    description: 'Achieve an 80 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-90',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 90,
    rewardXp: 350,
    title: 'Squat 90kg',
    description: 'Achieve a 90 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-100',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 100,
    rewardXp: 500,
    title: 'Squat 100kg Club',
    description: 'Break into the three-digit realm: 100 kg Estimated 1RM Back Squat.',
  },
  {
    id: 'ms-squat-110',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 110,
    rewardXp: 550,
    title: 'Squat 110kg',
    description: 'Achieve a 110 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-120',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 120,
    rewardXp: 600,
    title: 'Squat 120kg',
    description: 'Achieve a 120 kg Estimated 1RM on the Barbell Back Squat.',
  },
  {
    id: 'ms-squat-140',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 140,
    rewardXp: 800,
    title: 'Squat 140kg (3-Plate Milestone)',
    description: 'Legendary power: 140 kg Estimated 1RM Back Squat.',
  },
  {
    id: 'ms-squat-160',
    exerciseId: 'ex-barbell-back-squat',
    metric: 'BEST_E1RM',
    threshold: 160,
    rewardXp: 1000,
    title: 'Squat 160kg Ascendant',
    description: 'Elite domain: 160 kg Estimated 1RM Back Squat.',
  },

  // BENCH PRESS (ex-bench-press)
  {
    id: 'ms-bench-40',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 40,
    rewardXp: 100,
    title: 'Bench 40kg',
    description: 'Achieve a 40 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-50',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 50,
    rewardXp: 150,
    title: 'Bench 50kg',
    description: 'Achieve a 50 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-60',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 60,
    rewardXp: 200,
    title: 'Bench 60kg (1-Plate)',
    description: 'Achieve a 60 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-70',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 70,
    rewardXp: 250,
    title: 'Bench 70kg',
    description: 'Achieve a 70 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-80',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 80,
    rewardXp: 300,
    title: 'Bench 80kg',
    description: 'Achieve an 80 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-90',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 90,
    rewardXp: 350,
    title: 'Bench 90kg',
    description: 'Achieve a 90 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-100',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 100,
    rewardXp: 500,
    title: 'Bench 100kg (2-Plate Milestone)',
    description: 'The definitive iron milestone: 100 kg Estimated 1RM Bench Press.',
  },
  {
    id: 'ms-bench-110',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 110,
    rewardXp: 600,
    title: 'Bench 110kg',
    description: 'Achieve a 110 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-120',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 120,
    rewardXp: 750,
    title: 'Bench 120kg',
    description: 'Achieve a 120 kg Estimated 1RM on the Barbell Bench Press.',
  },
  {
    id: 'ms-bench-140',
    exerciseId: 'ex-bench-press',
    metric: 'BEST_E1RM',
    threshold: 140,
    rewardXp: 1000,
    title: 'Bench 140kg Apex',
    description: 'Colossal chest power: 140 kg Estimated 1RM Bench Press.',
  },

  // DEADLIFT (ex-barbell-deadlift)
  {
    id: 'ms-deadlift-60',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 60,
    rewardXp: 100,
    title: 'Deadlift 60kg',
    description: 'Achieve a 60 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-80',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 80,
    rewardXp: 150,
    title: 'Deadlift 80kg',
    description: 'Achieve an 80 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-100',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 100,
    rewardXp: 250,
    title: 'Deadlift 100kg',
    description: 'Achieve a 100 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-120',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 120,
    rewardXp: 350,
    title: 'Deadlift 120kg',
    description: 'Achieve a 120 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-140',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 140,
    rewardXp: 500,
    title: 'Deadlift 140kg (3-Plate)',
    description: 'Achieve a 140 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-160',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 160,
    rewardXp: 650,
    title: 'Deadlift 160kg',
    description: 'Achieve a 160 kg Estimated 1RM on the Barbell Deadlift.',
  },
  {
    id: 'ms-deadlift-180',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 180,
    rewardXp: 800,
    title: 'Deadlift 180kg (4-Plate Milestone)',
    description: 'Immense kinetic force: 180 kg Estimated 1RM Deadlift.',
  },
  {
    id: 'ms-deadlift-200',
    exerciseId: 'ex-barbell-deadlift',
    metric: 'BEST_E1RM',
    threshold: 200,
    rewardXp: 1000,
    title: 'Deadlift 200kg (Grandmaster Threshold)',
    description: 'Two quintals off the ground: 200 kg Estimated 1RM Deadlift.',
  },

  // OVERHEAD PRESS (ex-overhead-press)
  {
    id: 'ms-ohp-30',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 30,
    rewardXp: 100,
    title: 'OHP 30kg',
    description: 'Achieve a 30 kg Estimated 1RM on the Overhead Press.',
  },
  {
    id: 'ms-ohp-40',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 40,
    rewardXp: 150,
    title: 'OHP 40kg',
    description: 'Achieve a 40 kg Estimated 1RM on the Overhead Press.',
  },
  {
    id: 'ms-ohp-50',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 50,
    rewardXp: 250,
    title: 'OHP 50kg',
    description: 'Achieve a 50 kg Estimated 1RM on the Overhead Press.',
  },
  {
    id: 'ms-ohp-60',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 60,
    rewardXp: 400,
    title: 'OHP 60kg (1-Plate Overhead)',
    description: 'The golden pressing benchmark: 60 kg Estimated 1RM Overhead Press.',
  },
  {
    id: 'ms-ohp-70',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 70,
    rewardXp: 600,
    title: 'OHP 70kg',
    description: 'Achieve a 70 kg Estimated 1RM on the Overhead Press.',
  },
  {
    id: 'ms-ohp-80',
    exerciseId: 'ex-overhead-press',
    metric: 'BEST_E1RM',
    threshold: 80,
    rewardXp: 850,
    title: 'OHP 80kg Sovereign',
    description: 'Elite vertical force: 80 kg Estimated 1RM Overhead Press.',
  },

  // PULL-UP (ex-pullup)
  {
    id: 'ms-pullup-5',
    exerciseId: 'ex-pullup',
    metric: 'BEST_WEIGHT', // For bodyweight exercises, tracks max reps
    threshold: 5,
    rewardXp: 100,
    title: '5 Strict Pull-Ups',
    description: 'Perform 5 strict, full range-of-motion pull-ups in a single set.',
  },
  {
    id: 'ms-pullup-10',
    exerciseId: 'ex-pullup',
    metric: 'BEST_WEIGHT',
    threshold: 10,
    rewardXp: 250,
    title: '10 Strict Pull-Ups',
    description: 'Perform 10 strict, full range-of-motion pull-ups in a single set.',
  },
  {
    id: 'ms-pullup-15',
    exerciseId: 'ex-pullup',
    metric: 'BEST_WEIGHT',
    threshold: 15,
    rewardXp: 400,
    title: '15 Strict Pull-Ups',
    description: 'Perform 15 strict, full range-of-motion pull-ups in a single set.',
  },
  {
    id: 'ms-pullup-20',
    exerciseId: 'ex-pullup',
    metric: 'BEST_WEIGHT',
    threshold: 20,
    rewardXp: 600,
    title: '20 Strict Pull-Ups',
    description: 'Perform 20 strict, full range-of-motion pull-ups in a single set.',
  },
];
